version: "3"
services:
  513bot-core-receiver:
    image: 513bot-core-receiver
    build:
      context: .
      dockerfile: ./receive/Dockerfile
    environment:
      - SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN
      - SLACK_APP_TOKEN=$SLACK_APP_TOKEN
    container_name: 513bot-core-receiver
    volumes:
      - ./receive/app.py:/app.py:ro
    restart: always
  513bot-core-sender:
    image: 513bot-core-sender
    build:
      context: .
      dockerfile: ./send/Dockerfile
    environment:
      - SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN
      - SLACK_APP_TOKEN=$SLACK_APP_TOKEN
    container_name: 513bot-core-sender
    volumes:
      - ./send/app.py:/app.py:ro
    restart: always
networks:
  default:
    name: 513bot-network